# Authored in part or whole by ChatGPT
name: Windows Build with Visual Studio

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # - name: Setup MSVC Build Tools
      #   uses: microsoft/setup-msbuild@v2

      - name: Run CMake configure
        run: cmake -B build -S .

      - name: Build project
        run: cmake --build build --config Release

      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: StudentSync_Win32.zip
          path: | # Our RT deps are all DLLs or EXEs
            build/Release/*.dll
            build/Release/*.exe
          compression-level: 0 # binary files don't benefit much from compression, so just skip it
